#pragma once
#include "shader.h"
#include <iostream>
#include <string>
#include <vector>
#include <GL/glew.h>
#include <stdio.h>
#include <stdlib.h>
#include <GL/glut.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
